take google service version from environment if available
idehub/react-native-google-analytics-bridge pull request #229
Opened 2018-03-21 05:25 UTC by fattahmuhyiddeen

2018-03-21 08:11 UTC, cbrevik requested changes
Thanks for the PR! 🎉 Could you also add docs in `README.md` on how to use this?

2018-03-21 08:11 UTC, cbrevik commented on android/build.gradle
> +def DEFAULT_COMPILE_SDK_VERSION             = 23
Could you add the other project properties as well? For `compileSdkVersion `, `buildToolsVersion` and `targetSdkVersion`

2018-03-21 08:17 UTC, yangtaufoo commented
Thanks @fattahmuhyiddeen & @cbrevik!

2018-03-21 08:37 UTC, fattahmuhyiddeen commented
ok done put in README.md

2018-03-21 09:21 UTC, cbrevik approved these changes

2018-03-21 09:21 UTC, merged

2018-03-21 09:21 UTC, cbrevik commented
Awesome, thanks for this. It'll be included in the next version :+1:

2018-03-21 10:33 UTC, cbrevik commented
Published as `5.6.2`

2018-03-22 04:36 UTC, christocracy commented
Here’s a wiki entry in my [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Solving-Android-Gradle-Conflicts) module which nicely explains usage.  You might borrow chunks to add to your README.